name: Docs

on: [push]
permissions: 
  contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Rust
        uses: hecrj/setup-rust-action@v1
        
      - name: Generate Docs
        run: |
          sudo apt-get install libluajit-5.1-dev
          cargo doc --no-deps --all-features
          mv target/doc/nvim target/doc/docs
      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: target/doc
          git-config-name: ModBotProg
          git-config-email: bot@modprog.de
          clean: true
